"""empty message

Revision ID: 14fee81852cf
Revises: 06aa3f653563
Create Date: 2025-03-30 16:54:28.851555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fee81852cf'
down_revision: Union[str, None] = '06aa3f653563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('files_product_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_product_id_fkey', 'files', 'users', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###
