"""empty message

Revision ID: 3d5b45813a14
Revises: a0e46eb2b54e
Create Date: 2025-03-30 12:38:14.632263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5b45813a14'
down_revision: Union[str, None] = 'a0e46eb2b54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_yandex_id', table_name='users')
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.create_index('ix_users_yandex_id', 'users', ['yandex_id'], unique=False)
    # ### end Alembic commands ###
