"""empty message

Revision ID: a0e46eb2b54e
Revises: f901db78227c
Create Date: 2025-03-30 12:36:51.310976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e46eb2b54e'
down_revision: Union[str, None] = 'f901db78227c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
