"""empty message

Revision ID: cc9d3d070f85
Revises: 3d5b45813a14
Create Date: 2025-03-30 12:39:14.625137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc9d3d070f85'
down_revision: Union[str, None] = '3d5b45813a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('male', 'female', name='genders'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('male', 'female', name='genders'),
               nullable=False)
    # ### end Alembic commands ###
